// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package rest

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest(in *jlexer.Lexer, out *QuoteResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Data = make(map[string]map[string]QuoteData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 map[string]QuoteData
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v1 = make(map[string]QuoteData)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v2 QuoteData
							if in.IsNull() {
								in.Skip()
							} else {
								(v2).UnmarshalEasyJSON(in)
							}
							(v1)[key] = v2
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Data)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest(out *jwriter.Writer, in QuoteResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.Data {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				if v3Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v4First := true
					for v4Name, v4Value := range v3Value {
						if v4First {
							v4First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v4Name))
						out.RawByte(':')
						(v4Value).MarshalEasyJSON(out)
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v QuoteResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v QuoteResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *QuoteResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *QuoteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest1(in *jlexer.Lexer, out *QuoteData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "security_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SecurityID = int(in.Int())
			}
		case "last_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTradedPrice = float64(in.Float64())
			}
		case "last_traded_qty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTradedQty = int(in.Int())
			}
		case "last_traded_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTradedTime = string(in.String())
			}
		case "open":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Open = float64(in.Float64())
			}
		case "high":
			if in.IsNull() {
				in.Skip()
			} else {
				out.High = float64(in.Float64())
			}
		case "low":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Low = float64(in.Float64())
			}
		case "close":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Close = float64(in.Float64())
			}
		case "volume":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Volume = int64(in.Int64())
			}
		case "oi":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OpenInterest = int64(in.Int64())
			}
		case "avg_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvgTradedPrice = float64(in.Float64())
			}
		case "total_buy_qty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalBuyQty = int64(in.Int64())
			}
		case "total_sell_qty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalSellQty = int64(in.Int64())
			}
		case "lower_circuit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LowerCircuit = float64(in.Float64())
			}
		case "upper_circuit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpperCircuit = float64(in.Float64())
			}
		case "bid":
			if in.IsNull() {
				in.Skip()
				out.Bid = nil
			} else {
				in.Delim('[')
				if out.Bid == nil {
					if !in.IsDelim(']') {
						out.Bid = make([]MarketDepthEntry, 0, 2)
					} else {
						out.Bid = []MarketDepthEntry{}
					}
				} else {
					out.Bid = (out.Bid)[:0]
				}
				for !in.IsDelim(']') {
					var v5 MarketDepthEntry
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Bid = append(out.Bid, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ask":
			if in.IsNull() {
				in.Skip()
				out.Ask = nil
			} else {
				in.Delim('[')
				if out.Ask == nil {
					if !in.IsDelim(']') {
						out.Ask = make([]MarketDepthEntry, 0, 2)
					} else {
						out.Ask = []MarketDepthEntry{}
					}
				} else {
					out.Ask = (out.Ask)[:0]
				}
				for !in.IsDelim(']') {
					var v6 MarketDepthEntry
					if in.IsNull() {
						in.Skip()
					} else {
						(v6).UnmarshalEasyJSON(in)
					}
					out.Ask = append(out.Ask, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest1(out *jwriter.Writer, in QuoteData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"security_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SecurityID))
	}
	{
		const prefix string = ",\"last_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.LastTradedPrice))
	}
	{
		const prefix string = ",\"last_traded_qty\":"
		out.RawString(prefix)
		out.Int(int(in.LastTradedQty))
	}
	{
		const prefix string = ",\"last_traded_time\":"
		out.RawString(prefix)
		out.String(string(in.LastTradedTime))
	}
	{
		const prefix string = ",\"open\":"
		out.RawString(prefix)
		out.Float64(float64(in.Open))
	}
	{
		const prefix string = ",\"high\":"
		out.RawString(prefix)
		out.Float64(float64(in.High))
	}
	{
		const prefix string = ",\"low\":"
		out.RawString(prefix)
		out.Float64(float64(in.Low))
	}
	{
		const prefix string = ",\"close\":"
		out.RawString(prefix)
		out.Float64(float64(in.Close))
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Int64(int64(in.Volume))
	}
	{
		const prefix string = ",\"oi\":"
		out.RawString(prefix)
		out.Int64(int64(in.OpenInterest))
	}
	{
		const prefix string = ",\"avg_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.AvgTradedPrice))
	}
	{
		const prefix string = ",\"total_buy_qty\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalBuyQty))
	}
	{
		const prefix string = ",\"total_sell_qty\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalSellQty))
	}
	{
		const prefix string = ",\"lower_circuit\":"
		out.RawString(prefix)
		out.Float64(float64(in.LowerCircuit))
	}
	{
		const prefix string = ",\"upper_circuit\":"
		out.RawString(prefix)
		out.Float64(float64(in.UpperCircuit))
	}
	{
		const prefix string = ",\"bid\":"
		out.RawString(prefix)
		if in.Bid == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Bid {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ask\":"
		out.RawString(prefix)
		if in.Ask == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Ask {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v QuoteData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v QuoteData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *QuoteData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *QuoteData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest1(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest2(in *jlexer.Lexer, out *OptionStrikeData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ce":
			if in.IsNull() {
				in.Skip()
				out.CE = nil
			} else {
				if out.CE == nil {
					out.CE = new(OptionData)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.CE).UnmarshalEasyJSON(in)
				}
			}
		case "pe":
			if in.IsNull() {
				in.Skip()
				out.PE = nil
			} else {
				if out.PE == nil {
					out.PE = new(OptionData)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.PE).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest2(out *jwriter.Writer, in OptionStrikeData) {
	out.RawByte('{')
	first := true
	_ = first
	if in.CE != nil {
		const prefix string = ",\"ce\":"
		first = false
		out.RawString(prefix[1:])
		(*in.CE).MarshalEasyJSON(out)
	}
	if in.PE != nil {
		const prefix string = ",\"pe\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.PE).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionStrikeData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionStrikeData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionStrikeData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionStrikeData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest2(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest3(in *jlexer.Lexer, out *OptionGreeks) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "delta":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Delta = float64(in.Float64())
			}
		case "theta":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Theta = float64(in.Float64())
			}
		case "gamma":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Gamma = float64(in.Float64())
			}
		case "vega":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Vega = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest3(out *jwriter.Writer, in OptionGreeks) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"delta\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Delta))
	}
	{
		const prefix string = ",\"theta\":"
		out.RawString(prefix)
		out.Float64(float64(in.Theta))
	}
	{
		const prefix string = ",\"gamma\":"
		out.RawString(prefix)
		out.Float64(float64(in.Gamma))
	}
	{
		const prefix string = ",\"vega\":"
		out.RawString(prefix)
		out.Float64(float64(in.Vega))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionGreeks) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionGreeks) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionGreeks) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionGreeks) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest3(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest4(in *jlexer.Lexer, out *OptionData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "security_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SecurityID = int(in.Int())
			}
		case "last_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastPrice = float64(in.Float64())
			}
		case "oi":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OpenInterest = int64(in.Int64())
			}
		case "volume":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Volume = int64(in.Int64())
			}
		case "prev_close":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevClose = float64(in.Float64())
			}
		case "prev_volume":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevVolume = int64(in.Int64())
			}
		case "implied_volatility":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImpliedVolatility = float64(in.Float64())
			}
		case "greeks":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Greeks).UnmarshalEasyJSON(in)
			}
		case "top_bid_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopBidPrice = float64(in.Float64())
			}
		case "top_bid_quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopBidQty = int(in.Int())
			}
		case "top_ask_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopAskPrice = float64(in.Float64())
			}
		case "top_ask_quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopAskQty = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest4(out *jwriter.Writer, in OptionData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"security_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SecurityID))
	}
	{
		const prefix string = ",\"last_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.LastPrice))
	}
	{
		const prefix string = ",\"oi\":"
		out.RawString(prefix)
		out.Int64(int64(in.OpenInterest))
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Int64(int64(in.Volume))
	}
	{
		const prefix string = ",\"prev_close\":"
		out.RawString(prefix)
		out.Float64(float64(in.PrevClose))
	}
	{
		const prefix string = ",\"prev_volume\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevVolume))
	}
	{
		const prefix string = ",\"implied_volatility\":"
		out.RawString(prefix)
		out.Float64(float64(in.ImpliedVolatility))
	}
	{
		const prefix string = ",\"greeks\":"
		out.RawString(prefix)
		(in.Greeks).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"top_bid_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.TopBidPrice))
	}
	{
		const prefix string = ",\"top_bid_quantity\":"
		out.RawString(prefix)
		out.Int(int(in.TopBidQty))
	}
	{
		const prefix string = ",\"top_ask_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.TopAskPrice))
	}
	{
		const prefix string = ",\"top_ask_quantity\":"
		out.RawString(prefix)
		out.Int(int(in.TopAskQty))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest4(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest5(in *jlexer.Lexer, out *OptionChainResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Data).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest5(out *jwriter.Writer, in OptionChainResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		(in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionChainResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionChainResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionChainResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionChainResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest5(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest6(in *jlexer.Lexer, out *OptionChainRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "UnderlyingScrip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnderlyingScrip = int(in.Int())
			}
		case "UnderlyingSeg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnderlyingSeg = string(in.String())
			}
		case "Expiry":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Expiry = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest6(out *jwriter.Writer, in OptionChainRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UnderlyingScrip\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UnderlyingScrip))
	}
	if in.UnderlyingSeg != "" {
		const prefix string = ",\"UnderlyingSeg\":"
		out.RawString(prefix)
		out.String(string(in.UnderlyingSeg))
	}
	if in.Expiry != "" {
		const prefix string = ",\"Expiry\":"
		out.RawString(prefix)
		out.String(string(in.Expiry))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionChainRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionChainRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionChainRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionChainRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest6(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest7(in *jlexer.Lexer, out *OptionChainData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "last_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastPrice = float64(in.Float64())
			}
		case "oc":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.OC = make(map[string]OptionStrikeData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 OptionStrikeData
					if in.IsNull() {
						in.Skip()
					} else {
						(v11).UnmarshalEasyJSON(in)
					}
					(out.OC)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest7(out *jwriter.Writer, in OptionChainData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"last_price\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.LastPrice))
	}
	{
		const prefix string = ",\"oc\":"
		out.RawString(prefix)
		if in.OC == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.OC {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				(v12Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionChainData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionChainData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionChainData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionChainData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest7(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest8(in *jlexer.Lexer, out *OHLCResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Data = make(map[string]map[string]OHLCData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v13 map[string]OHLCData
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v13 = make(map[string]OHLCData)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v14 OHLCData
							if in.IsNull() {
								in.Skip()
							} else {
								(v14).UnmarshalEasyJSON(in)
							}
							(v13)[key] = v14
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Data)[key] = v13
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest8(out *jwriter.Writer, in OHLCResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.Data {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				if v15Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v16First := true
					for v16Name, v16Value := range v15Value {
						if v16First {
							v16First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v16Name))
						out.RawByte(':')
						(v16Value).MarshalEasyJSON(out)
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OHLCResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OHLCResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OHLCResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OHLCResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest8(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest9(in *jlexer.Lexer, out *OHLCData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "security_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SecurityID = int(in.Int())
			}
		case "last_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTradedPrice = float64(in.Float64())
			}
		case "open":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Open = float64(in.Float64())
			}
		case "high":
			if in.IsNull() {
				in.Skip()
			} else {
				out.High = float64(in.Float64())
			}
		case "low":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Low = float64(in.Float64())
			}
		case "close":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Close = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest9(out *jwriter.Writer, in OHLCData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"security_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SecurityID))
	}
	{
		const prefix string = ",\"last_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.LastTradedPrice))
	}
	{
		const prefix string = ",\"open\":"
		out.RawString(prefix)
		out.Float64(float64(in.Open))
	}
	{
		const prefix string = ",\"high\":"
		out.RawString(prefix)
		out.Float64(float64(in.High))
	}
	{
		const prefix string = ",\"low\":"
		out.RawString(prefix)
		out.Float64(float64(in.Low))
	}
	{
		const prefix string = ",\"close\":"
		out.RawString(prefix)
		out.Float64(float64(in.Close))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OHLCData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OHLCData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OHLCData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OHLCData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest9(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest10(in *jlexer.Lexer, out *MarketDepthEntry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantity = int(in.Int())
			}
		case "orders":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Orders = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest10(out *jwriter.Writer, in MarketDepthEntry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int(int(in.Quantity))
	}
	{
		const prefix string = ",\"orders\":"
		out.RawString(prefix)
		out.Int(int(in.Orders))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MarketDepthEntry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MarketDepthEntry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MarketDepthEntry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MarketDepthEntry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest10(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest11(in *jlexer.Lexer, out *LTPResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Data = make(map[string]map[string]LTPData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v17 map[string]LTPData
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v17 = make(map[string]LTPData)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v18 LTPData
							if in.IsNull() {
								in.Skip()
							} else {
								(v18).UnmarshalEasyJSON(in)
							}
							(v17)[key] = v18
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Data)[key] = v17
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest11(out *jwriter.Writer, in LTPResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v19First := true
			for v19Name, v19Value := range in.Data {
				if v19First {
					v19First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v19Name))
				out.RawByte(':')
				if v19Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v20First := true
					for v20Name, v20Value := range v19Value {
						if v20First {
							v20First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v20Name))
						out.RawByte(':')
						(v20Value).MarshalEasyJSON(out)
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LTPResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LTPResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LTPResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LTPResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest11(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest12(in *jlexer.Lexer, out *LTPData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "security_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SecurityID = int(in.Int())
			}
		case "last_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTradedPrice = float64(in.Float64())
			}
		case "last_traded_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTradedTime = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest12(out *jwriter.Writer, in LTPData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"security_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SecurityID))
	}
	{
		const prefix string = ",\"last_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.LastTradedPrice))
	}
	if in.LastTradedTime != "" {
		const prefix string = ",\"last_traded_time\":"
		out.RawString(prefix)
		out.String(string(in.LastTradedTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LTPData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LTPData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LTPData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LTPData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest12(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest13(in *jlexer.Lexer, out *ExpiryListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]string, 0, 4)
					} else {
						out.Data = []string{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v21 string
					if in.IsNull() {
						in.Skip()
					} else {
						v21 = string(in.String())
					}
					out.Data = append(out.Data, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest13(out *jwriter.Writer, in ExpiryListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v22, v23 := range in.Data {
				if v22 > 0 {
					out.RawByte(',')
				}
				out.String(string(v23))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExpiryListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExpiryListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExpiryListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExpiryListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest13(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest14(in *jlexer.Lexer, out *ExpiryListRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "UnderlyingScrip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnderlyingScrip = int(in.Int())
			}
		case "UnderlyingSeg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnderlyingSeg = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest14(out *jwriter.Writer, in ExpiryListRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UnderlyingScrip\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UnderlyingScrip))
	}
	if in.UnderlyingSeg != "" {
		const prefix string = ",\"UnderlyingSeg\":"
		out.RawString(prefix)
		out.String(string(in.UnderlyingSeg))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExpiryListRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExpiryListRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoRest14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExpiryListRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExpiryListRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoRest14(l, v)
}
