// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package orderupdate

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoOrderupdate(in *jlexer.Lexer, out *OrderAlertData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "orderNo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderID = string(in.String())
			}
		case "ExchOrderNo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExchangeOrderID = string(in.String())
			}
		case "dhanClientId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientID = string(in.String())
			}
		case "correlationId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CorrelationID = string(in.String())
			}
		case "tradingSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "securityId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SecurityID = string(in.String())
			}
		case "exchangeSegment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exchange = string(in.String())
			}
		case "productType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProductType = string(in.String())
			}
		case "orderType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderType = string(in.String())
			}
		case "validity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Validity = string(in.String())
			}
		case "transactionType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TransactionType = string(in.String())
			}
		case "quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantity = int32(in.Int32())
			}
		case "disclosedQuantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DisclosedQty = int32(in.Int32())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float32(in.Float32())
			}
		case "triggerPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TriggerPrice = float32(in.Float32())
			}
		case "TradedQty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradedQuantity = int32(in.Int32())
			}
		case "TradedPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradedPrice = float32(in.Float32())
			}
		case "AvgTradedPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvgTradedPrice = float32(in.Float32())
			}
		case "remainingQuantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RemainingQty = int32(in.Int32())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "orderStatus":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderStatus = string(in.String())
			}
		case "ReasonCode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReasonCode = string(in.String())
			}
		case "ReasonDescription":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReasonDescription = string(in.String())
			}
		case "expiryDate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiryDate = string(in.String())
			}
		case "strikePrice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StrikePrice = float32(in.Float32())
			}
		case "optionType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OptionType = string(in.String())
			}
		case "instrumentType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InstrumentType = string(in.String())
			}
		case "orderDateTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderDateTime = string(in.String())
			}
		case "exchOrderTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExchangeTime = string(in.String())
			}
		case "lastUpdatedTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastUpdatedTime = string(in.String())
			}
		case "boProfitValue":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BOProfitValue = float32(in.Float32())
			}
		case "boStopLossValue":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BOStopLossValue = float32(in.Float32())
			}
		case "legName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LegName = string(in.String())
			}
		case "afterMarketOrder":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AfterMarketOrder = bool(in.Bool())
			}
		case "amoTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AmoTime = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoOrderupdate(out *jwriter.Writer, in OrderAlertData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"orderNo\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"ExchOrderNo\":"
		out.RawString(prefix)
		out.String(string(in.ExchangeOrderID))
	}
	{
		const prefix string = ",\"dhanClientId\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	if in.CorrelationID != "" {
		const prefix string = ",\"correlationId\":"
		out.RawString(prefix)
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"tradingSymbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"securityId\":"
		out.RawString(prefix)
		out.String(string(in.SecurityID))
	}
	{
		const prefix string = ",\"exchangeSegment\":"
		out.RawString(prefix)
		out.String(string(in.Exchange))
	}
	{
		const prefix string = ",\"productType\":"
		out.RawString(prefix)
		out.String(string(in.ProductType))
	}
	{
		const prefix string = ",\"orderType\":"
		out.RawString(prefix)
		out.String(string(in.OrderType))
	}
	{
		const prefix string = ",\"validity\":"
		out.RawString(prefix)
		out.String(string(in.Validity))
	}
	{
		const prefix string = ",\"transactionType\":"
		out.RawString(prefix)
		out.String(string(in.TransactionType))
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int32(int32(in.Quantity))
	}
	if in.DisclosedQty != 0 {
		const prefix string = ",\"disclosedQuantity\":"
		out.RawString(prefix)
		out.Int32(int32(in.DisclosedQty))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float32(float32(in.Price))
	}
	if in.TriggerPrice != 0 {
		const prefix string = ",\"triggerPrice\":"
		out.RawString(prefix)
		out.Float32(float32(in.TriggerPrice))
	}
	if in.TradedQuantity != 0 {
		const prefix string = ",\"TradedQty\":"
		out.RawString(prefix)
		out.Int32(int32(in.TradedQuantity))
	}
	if in.TradedPrice != 0 {
		const prefix string = ",\"TradedPrice\":"
		out.RawString(prefix)
		out.Float32(float32(in.TradedPrice))
	}
	if in.AvgTradedPrice != 0 {
		const prefix string = ",\"AvgTradedPrice\":"
		out.RawString(prefix)
		out.Float32(float32(in.AvgTradedPrice))
	}
	if in.RemainingQty != 0 {
		const prefix string = ",\"remainingQuantity\":"
		out.RawString(prefix)
		out.Int32(int32(in.RemainingQty))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"orderStatus\":"
		out.RawString(prefix)
		out.String(string(in.OrderStatus))
	}
	if in.ReasonCode != "" {
		const prefix string = ",\"ReasonCode\":"
		out.RawString(prefix)
		out.String(string(in.ReasonCode))
	}
	if in.ReasonDescription != "" {
		const prefix string = ",\"ReasonDescription\":"
		out.RawString(prefix)
		out.String(string(in.ReasonDescription))
	}
	if in.ExpiryDate != "" {
		const prefix string = ",\"expiryDate\":"
		out.RawString(prefix)
		out.String(string(in.ExpiryDate))
	}
	if in.StrikePrice != 0 {
		const prefix string = ",\"strikePrice\":"
		out.RawString(prefix)
		out.Float32(float32(in.StrikePrice))
	}
	if in.OptionType != "" {
		const prefix string = ",\"optionType\":"
		out.RawString(prefix)
		out.String(string(in.OptionType))
	}
	if in.InstrumentType != "" {
		const prefix string = ",\"instrumentType\":"
		out.RawString(prefix)
		out.String(string(in.InstrumentType))
	}
	{
		const prefix string = ",\"orderDateTime\":"
		out.RawString(prefix)
		out.String(string(in.OrderDateTime))
	}
	if in.ExchangeTime != "" {
		const prefix string = ",\"exchOrderTime\":"
		out.RawString(prefix)
		out.String(string(in.ExchangeTime))
	}
	if in.LastUpdatedTime != "" {
		const prefix string = ",\"lastUpdatedTime\":"
		out.RawString(prefix)
		out.String(string(in.LastUpdatedTime))
	}
	if in.BOProfitValue != 0 {
		const prefix string = ",\"boProfitValue\":"
		out.RawString(prefix)
		out.Float32(float32(in.BOProfitValue))
	}
	if in.BOStopLossValue != 0 {
		const prefix string = ",\"boStopLossValue\":"
		out.RawString(prefix)
		out.Float32(float32(in.BOStopLossValue))
	}
	if in.LegName != "" {
		const prefix string = ",\"legName\":"
		out.RawString(prefix)
		out.String(string(in.LegName))
	}
	if in.AfterMarketOrder {
		const prefix string = ",\"afterMarketOrder\":"
		out.RawString(prefix)
		out.Bool(bool(in.AfterMarketOrder))
	}
	if in.AmoTime != "" {
		const prefix string = ",\"amoTime\":"
		out.RawString(prefix)
		out.String(string(in.AmoTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderAlertData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoOrderupdate(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderAlertData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoOrderupdate(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderAlertData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoOrderupdate(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderAlertData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoOrderupdate(l, v)
}
func easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoOrderupdate1(in *jlexer.Lexer, out *OrderAlert) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "Data":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Data).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoOrderupdate1(out *jwriter.Writer, in OrderAlert) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"Data\":"
		out.RawString(prefix)
		(in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderAlert) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoOrderupdate1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderAlert) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComSamarthkathalDhanGoOrderupdate1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderAlert) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoOrderupdate1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderAlert) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComSamarthkathalDhanGoOrderupdate1(l, v)
}
